version: '3'
services:
  student_service:
    build: .
    image: ${REPO_NAME}/${IMAGE_NAME}:latest
    container_name: student_service
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      DB_NAME: "student_db"
      COLLECTION_NAME: "students"
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo_student
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
